### ISSUE TITLE
Is supporting rust 1.0 still needed?

### ISSUE THREAD

**Issue by oyvindln** [image-rs/inflate#21]
It makes sense to not be dependent on the absulote latest rust version, but 1.0 seems a bit of a stretch as it e.g doesn't support `?` which would make it hard to [follow the library guidelines](https://github.com/brson/rust-api-guidelines#c-question-mark).

**Comment by nwin** [comment]
As long it is not a big pain I do not see any benefit of dropping 1.0 support. So far I see no features which would justify dropping 1.0 support. Using ? Instead of try! would mean dropping support for everything below 1.13 not just 1.0. 

Besides, the guidelines are just guidelines. If you can't follow them no harm is done.

**Comment by martinlindhe** [comment]
I sent a pr about using ? and bumping min stable version to 1.13 in #54

I hope this is not still controversial :-)

**Comment by martinlindhe** [comment]
Closing issue as resolved with #54
